### ISSUE TITLE
Exception in HostFunction: No such file or directory (os error 2)

### ISSUE THREAD

**Issue by dwightwatson** [prisma/react-native-prisma#10]
Trying to get this going in an Expo project and not having much luck so far.

* Installed into a new-ish Expo project
* Added the plugin to `app.json`
* Added `schema.primsa` to the root directory
* Ran `npx prisma@latest generate`
* Called `runMigrations` from the root component

```js
export const runMigrations = async () => {
  try {
    await baseClient.$applyPendingMigrations();
  } catch (e) {
    console.error(`failed to apply migrations: ${e}`);

    throw new Error(
      "Applying migrations failed, your app is now in an inconsistent state. We cannot guarantee safety, it is now your responsability to reset the database or tell the user to re-install the app",
    );
  }
};
```

The error thrown is `Exception in HostFunction: No such file or directory (os error 2)`

I am newer to Prisma so did some doc-diving and thought perhaps I needed to run `npx prisma migrate dev` which generated a `migrations` directory, `app.db` and `app.db-journal` in my root directory, but this wasn't mentioned in the docs and also didn't solve the problem.

**Comment by sorenbs** [comment]
Hi Dwight 👋 

It sounds like you might have the wrong version of Prisma running. Did you edit the schema.prisma file to enable the preview feature as documented in the readme?

```
generator client {
  provider = "prisma-client-js"
  previewFeatures = ["reactNative"] // <- this line is important !!!
}
```

You can simply add that line and re-run the generate command:

`npx prisma@latest generate`

**Comment by dwightwatson** [comment]
Hey Søren,

Thanks for that - I re-ran the installation command from the docs which looks like it should have installed the latest versions of each package. Here are the versions shown from `package-lock.json`:

```
"@prisma/client": "^5.14.0",
"@prisma/react-native": "^5.14.0",
"react-native-quick-base64": "^2.1.2",
```

I copied the `schema.prisma` from the docs and just changed the model.

```
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["reactNative"]
}

datasource db {
  provider = "sqlite"
  url      = "file:./app.db"
}

// Your data model

model Category {
  id           Int     @id @default(autoincrement())
  name         String
  description  String?
  defaultOrder String
  order        Int
  small        String?
  large        String?
}
```

And here is the output from the generate command:

````
✗ npx prisma@latest generate
Need to install the following packages:
prisma@5.14.0
Ok to proceed? (y) y

Environment variables loaded from .env
Prisma schema loaded from schema.prisma

✔ Generated Prisma Client (v5.14.0) to ./node_modules/@prisma/client in 48ms

Start using Prisma Client in Node.js (See: https://pris.ly/d/client)
```
import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()
```
or start using Prisma Client at the edge (See: https://pris.ly/d/accelerate)
```
import { PrismaClient } from '@prisma/client/edge'
const prisma = new PrismaClient()
```

See other ways of importing Prisma Client: http://pris.ly/d/importing-client

┌─────────────────────────────────────────────────────────────┐
│  Deploying your app to serverless or edge functions?        │
│  Try Prisma Accelerate for connection pooling and caching.  │
│  https://pris.ly/cli/--accelerate                           │
└─────────────────────────────────────────────────────────────┘
````

Are there any clues in there? (Do I need to run `npx prisma migrate dev` in the context of a RN app or is that not relevant?)

**Comment by sorenbs** [comment]
Okay, I think I understand what is happening.

You must run `npx expo prebuild --clean` once after adding the expo extension. Can you try to run it once and see if that resolves the issue for you? The extension takes care of copying the database and migrations files to the simulator, so when it is not set up correctly, that results in the `No such file or directory` error you are seeing.

I have updated the Readme to makes this more clear.

Thank you for reporting this!

**Comment by dwightwatson** [comment]
I had been using EAS build - but yes, after running `npx prisma migrate dev` and then `eas build --profile=development` this appears to work now. Thanks for that!

It does feel a little icky to have the `app.db` present in the repo as conceptually it feels like that should live inside the app only. Do you think this will always be a requirement or something that could be handled automatically eventually?

**Comment by sorenbs** [comment]
Excellent!

Having the db in the repo isn't strictly required, and I agree it's a bit weird. I think we should have an easy way to connect a db viewer to the db running on a device/simulator during development, and then do away with that db in the repo.

Do you have a preference between a standard tool such as [SQLite Viewer](https://marketplace.visualstudio.com/items?itemName=qwtel.sqlite-viewer) for VS Code vs [Prisma Studio](https://www.prisma.io/studio)?

**Comment by dwightwatson** [comment]
Honestly - I'm brand new to Prisma, so I don't have any knowledge/preference on the matter. 

Being able to connect directly to the database running on a device or simulator sounds like an incredible tool in debugging and understanding what's going on.

I'll close this issue now anyway as the original problem is now resolved.
